### ISSUE TITLE
第一句就有不通的地方……

### ISSUE THREAD

**Issue by xubeiyan** [phodal/github-roam#13]
比如

> 那时才大一，在那之后的那长日子里我都没有过到。

读了N遍之后感觉是说“在那之后很长时间都没有用过”的意思？

**Comment by phodal** [comment]
直接来个PR?

**Comment by xubeiyan** [comment]
不弄PullRequest……又不是代码……文字这种东西我觉得自己写就好……再说我根本没理解清楚这句话到底想表达个什么……

**Comment by binarywang** [comment]
我也有同感， 确实有些文字感觉不太通顺

**Comment by phodal** [comment]
@xubeiyan @binarywang 那我再改一下
