### ISSUE TITLE
No English repository description

### ISSUE THREAD

**Issue by vi** [phodal/github-roam#3]
There should be English description in addition to Chinese one.

The repository received enogh starts to appear on the [trending page](https://github.com/trending), but the the lack of English description makes it look uninviting.

**Comment by phodal** [comment]
Hi @vi ,

It's a ebook of introduction for people on how to explore, build project in GitHub.

**Comment by phodal** [comment]
already update

**Comment by vi** [comment]
Now looks OK, but the book is in Chinese, so the description should probably say `a Chinese ebook ...` instead of just `a ebook`.

Also some description in Chinese in addition to the English one should be useful.

The repository description is important because of it is the only thing being immediately visible in Search (apart from that it is HTML).

**Comment by phodal** [comment]
@vi Thanks for your suggestion. I will try to do it.
