### ISSUE TITLE
from README.md cannot access sub topic by hyperlink (例如前言etc.) 

### ISSUE THREAD

**Issue by Miiiian** [phodal/github-roam#74]
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/71177332/185114603-1084bd39-7629-479d-8f08-32d03024e2b7.png">
404 Not found

**Comment by phodal** [comment]
看上去像是个浏览器问题？ https://github.phodal.com/#/chapter/Github%E6%BC%AB%E6%B8%B8%E6%8C%87%E5%8D%97?id=%e5%89%8d%e8%a8%80

**Comment by Miiiian** [comment]
> 看上去像是个浏览器问题？ https://github.phodal.com/#/chapter/Github%E6%BC%AB%E6%B8%B8%E6%8C%87%E5%8D%97?id=%e5%89%8d%e8%a8%80

应该不是吧哈哈哈哈 我看了一下我这边加载的html代码 然后在Safari上也测试了 直接从README.md点超链接的话是404 clone下来的点也是 应该是README.md里面的超链接指向链接错了？ 我晚点有空的话Pull Request吧～ （刚入学会git比较小白 我晚点研究研究怎么Pull Request）
<img width="822" alt="image" src="https://user-images.githubusercontent.com/71177332/185115259-66b970b1-16ad-460a-a1e9-2b74ecfdef9a.png">

**Comment by phodal** [comment]
哦，那应该是 README 里的问题了，之前有一个小伙伴，改了主题：https://github.phodal.com/

**Comment by Miiiian** [comment]
> 哦，那应该是 README 里的问题了，之前有一个小伙伴，改了主题：https://github.phodal.com/

谢谢 我前面找到了这个漫游指南的正确链接啦
