### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by Bashamega** [phodal/github-roam#81]
I think this repo is cool and more people should know it.
I was thinking of contributing by updating the website for this repo so that people can find it on search engines.
I was think of using [docsify ](https://docsify.js.org/)and I think it will look great.

**Comment by phodal** [comment]
welcome

**Comment by Bashamega** [comment]
> welcome

can i work on it_

**Comment by phodal** [comment]
@Bashamega Yes, you can work on it.
